wip

diff --git a/scripts/build-cf-deps-tar b/scripts/build-cf-deps-tar
--- a/scripts/build-cf-deps-tar
+++ b/scripts/build-cf-deps-tar
@@ -4,18 +4,35 @@ output_dir="$dir"/../build
 
 set -ex
 
-while getopts "m:s:c:" arg; do
+while getopts "m:s:c:b:" arg; do
   case $arg in
     m) manifest="$OPTARG"
       ;;
-    s) stemcell_url="$OPTARG"
+    b) manifest="$OPTARG"
+      ;;
+    s) compilation_stemcell="$OPTARG"
       ;;
     c) cloud_config="$OPTARG"
   esac
 done
 
+if [[ -z $manifest || -z $compilation_stemcell || -z $cloud_config ]]; then
+  echo "USAGE: build-cf-deps-tar -m <path-to-cf-manifest> -s <path-to-compilation> -c <path-to-cloud-config>"
+  exit 2
+fi
+
+if [[ -z "$BOSH_ENVIRONMENT" ]]; then
+  echo "ERROR: a bosh director is required to compile releases, please set your BOSH_* env variables"
+  exit 3
+fi
+
 releases_dir="$(mktemp -d)"
 mkdir -p "$releases_dir"
+trap cleanup EXIT
+
+cleanup () {
+  rm -rf "$releases_dir"
+}
 
 stemcell_version () {
   rq -y <"$manifest" | jq -r '.stemcells[0].version'
@@ -36,10 +53,15 @@ download_compiled_releases () {
 compile_releases () {
     releases_to_compile="$(rq -y <"$manifest" | jq -r '.releases[] | select(has("stemcell") | not) | "\(.name)/\(.version)"')"
     compilation_manifest="$(rq -y <"$manifest" | jq 'del(.instance_groups) | del(.addons) | del(.variables)' | rq -Y)"
-    bosh upload-stemcell "$stemcell_url"
+    bosh upload-stemcell "$compilation_stemcell"
     bosh -n deploy -d cf <(echo "$compilation_manifest")
     for release in $releases_to_compile; do
-      bosh -d cf export-release "$release" ubuntu-trusty/"$(stemcell_version)" --dir "$releases_dir"
+      if [[ "$release" =~ bosh-dns* ]]; then
+        ## we cant compile bosh-dns-windows so only compile the linux job
+        bosh -d cf export-release "$release" ubuntu-trusty/"$(stemcell_version)" --dir "$releases_dir" --job bosh-dns
+      else
+        bosh -d cf export-release "$release" ubuntu-trusty/"$(stemcell_version)" --dir "$releases_dir"
+      fi
     done
 }
 
@@ -49,12 +71,11 @@ tar_deps () {
   pushd "$releases_dir"
     tar czf "$output_dir"/cf.tgz *
   popd
-  rm -rf "$releases_dir"
 }
 
 main () {
-  # download_warden_stemcell
-  # download_compiled_releases
+  download_warden_stemcell
+  download_compiled_releases
   compile_releases
   tar_deps
 }
